---
global:
  namespace: services
  project: services
  repo:
    url: https://github.com/vladimir-babichev/home-infra/
    revision: HEAD
  plugin:
    name: argocd-vault-plugin-helm

argocd-apps:
  applications:
    babybuddy:
      path: k8s/services/babybuddy
    pihole:
      path: k8s/services/pihole
    unifi:
      path: k8s/services/unifi
