nameOverride: gitops-apps
global:
  gitops:
    namespace: default
  namespace: default
  project: default
  repo:
    url: https://github.com/vladimir-babichev/gitops-argocd/
    revision: HEAD
    pathPrefix: k8s/gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

applications:
  gitops-apps:
    path: k8s/gitops/apps
    namespace: default
    helm:
      releaseName: gitops-apps
      version: v3
      valueFiles:
        - values.yaml
  core-apps:
    path: k8s/core/apps
    helm:
      releaseName: core-apps
      version: v3
      valueFiles:
        - values.yaml
  argocd:
    path: k8s/gitops/argocd
