.appproj-annotations: &x-appproj-annotations
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
global:
  namespace: gitops
  project: gitops
  repo:
    url: https://github.com/vladimir-babichev/gitops-argocd/
    revision: HEAD

argocd-apps:
  applications:
    argocd:
      path: k8s/gitops/argocd
      plugin:
        name: argocd-vault-plugin-helm
    gitops-apps:
      path: k8s/gitops/apps
    core-apps:
      path: k8s/core/apps
    ingress-apps:
      path: k8s/ingress/apps

  appProjects:
    core:
      <<: *x-appproj-annotations
      destinations:
        - namespace: core
          server: https://kubernetes.default.svc
        - namespace: ingress-internal
          server: https://kubernetes.default.svc
        - namespace: ingress-external
          server: https://kubernetes.default.svc
    gitops:
      <<: *x-appproj-annotations
      destinations:
        - namespace: gitops
          server: https://kubernetes.default.svc
    home-automation:
      <<: *x-appproj-annotations
      destinations:
        - namespace: home-automation
          server: https://kubernetes.default.svc
    services:
      <<: *x-appproj-annotations
      destinations:
        - namespace: gitlab
          server: https://kubernetes.default.svc
        - namespace: services
          server: https://kubernetes.default.svc
    system-upgrade:
      <<: *x-appproj-annotations
      destinations:
        - namespace: system-upgrade
          server: https://kubernetes.default.svc
