###
# Templated values
###
.affinity: &x-affinity
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64

.domain: &x-domain "argocd.bornin.su"
.url: &x-url "https://argocd.bornin.su"
.metrics: &x-metrics
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false


###
# Configuration
###
externalSecret:
  argocd-manor-gitrepo:
    refreshInterval: "10m"
    secretStoreRef:
      name: vault
      kind: ClusterSecretStore
    target:
      name: argocd-manor-gitrepo
      template:
        metadata:
          labels:
            argocd.argoproj.io/secret-type: repo-creds
        data:
          type: git
          url: git@gitlab-gitlab-shell.gitlab.svc:manor
          sshPrivateKey: |
            {{ .sshPrivateKey | toString }}
    data:
      - secretKey: sshPrivateKey
        remoteRef:
          key: k8s/argocd/sshKey
          property: sshPrivateKey

argo-cd:
  global:
    image:
      tag: v2.0.1

  server:
    <<: *x-affinity
    <<: *x-metrics
    extraArgs:
      - --insecure
    config:
      application.instanceLabelKey: argocd.argoproj.io/instance
      repositories: |
        - name: argo
          type: helm
          url: https://argoproj.github.io/argo-helm
        - name: stable
          type: helm
          url: https://charts.helm.sh/stable
      url: *x-url
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/ingress.class: traefik-internal
      enabled: true
      hosts:
        - *x-domain
      paths:
        - /
      tls:
      - secretName: *x-domain
        hosts:
        - *x-domain

  controller:
    <<: *x-affinity
    <<: *x-metrics

  dex:
    <<: *x-affinity
    <<: *x-metrics
    ebabled: false

  repoServer:
    <<: *x-affinity
    <<: *x-metrics
