nfs-subdir-external-provisioner:
  nfs:
    server: <path:secrets/data/k8s/nfs/secrets#server>
    path: <path:secrets/data/k8s/nfs/secrets#path>

  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
