---
global:
  namespace: core
  project: core
  repo:
    url: https://github.com/vladimir-babichev/gitops-argocd/
    revision: HEAD

argocd-apps:
  applications:
    nfs-subdir-external-provisioner:
      path: k8s/core/nfs-subdir-external-provisioner
      plugin:
        name: argocd-vault-plugin-helm
    vault:
      path: k8s/core/vault
      plugin:
        name: argocd-vault-plugin-helm
    cert-manager:
      path: k8s/core/cert-manager
      plugin:
        name: argocd-vault-plugin-helm
    metallb:
      path: k8s/core/cert-manager
    mysql:
      path: k8s/core/mysql
      plugin:
        name: argocd-vault-plugin-helm
