---
name: Deploy Docs

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docs.yaml"
      - "mkdocs.yaml"
      - "docs/**"

jobs:
  publish-docs:
    name: Publish Docs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Configure Git Author
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Install dependencies
        run: make docs-setup
      - name: Publish Docs
        run: make docs-publish
